#!/bin/bash

choice=$(cat /etc/ssh/host_list | fzf --prompt="Connect to Server:" | awk -F'|' '{gsub(/\t/, " "); gsub(/^ +| +$/, "", $1); print $1}')

if [[ "$choice" == "EDIT" ]]; then
    sudo vim /etc/ssh/host_list
elif [[ "$choice" != "" ]]; then
    ssh "$choice"
fi
